export const marketContent = {
  SN: {
    lang: "fr",
    marketLabel: "Sénégal",
    marketEyebrow: "Pour les entreprises au Sénégal",
    pickerTitle: "Où se trouve votre entreprise ?",
    pickerCopy: "Choisissez votre marché pour afficher l’expérience, les tarifs et les modalités adaptés à votre pays.",
    pickerAction: "Voir la version Sénégal",
    nav: ["Le modèle", "Tarifs", "Méthode", "FAQ"],
    navCta: "Obtenir mon aperçu",
    heroEyebrow: "SOCLE — Site professionnel au Sénégal",
    heroTitle: <>Un site qui donne du <em>poids</em> à votre expertise.</>,
    heroLead: "Une présence professionnelle pensée pour les usages locaux : mobile, WhatsApp et contact direct. Le site vous appartient, sans abonnement obligatoire.",
    heroPrimary: "Recevoir mon aperçu",
    heroSecondary: "Voir le tarif Sénégal",
    heroMeta: [["01 / Format", "Jusqu’à 5 pages"], ["02 / Aperçu", "Personnalisé sous 72 h"], ["03 / Lancement", "En 7 à 10 jours ouvrés"]],
    stripTitle: "Pensé pour convertir au Sénégal",
    stripItems: ["Mobile", "WhatsApp", "Appels directs", "Google Maps"],
    modelEyebrow: "Un investissement. Un actif qui vous appartient.",
    modelTitle: <>Une présence crédible.<br /><em>Adaptée au marché sénégalais.</em></>,
    modelCopy: [
      "Vos clients vous découvrent souvent depuis leur téléphone et veulent pouvoir vous contacter immédiatement. SOCLE présente clairement votre activité et les guide vers WhatsApp, l’appel ou votre adresse.",
      "Une fois le projet réglé, le code, les fichiers et les accès vous sont remis. Vous restez libre de gérer votre site vous-même, avec STATURE ou avec le prestataire de votre choix.",
    ],
    pricingEyebrow: "Tarif Sénégal",
    pricingTitle: <>Votre site en pleine propriété.<br />Deux façons de régler.</>,
    pricingIntro: "Un tarif transparent en FCFA, sans mensualité obligatoire. Choisissez simplement le rythme de paiement qui convient à votre trésorerie.",
    offerBadge: "À vous, définitivement",
    offerTitle: <>Un site professionnel.<br />Un actif qui vous appartient.</>,
    offerCopy: "Design, développement, mise en ligne et transfert complet des accès. Aucun engagement mensuel.",
    features: ["Jusqu’à 5 pages personnalisées", "Version mobile, WhatsApp, appels et formulaire", "Google Maps, SEO essentiel et statistiques", "Domaine, SSL et mise en ligne accompagnée", "Code source et accès remis après règlement"],
    referencePrice: "Tarif de référence — Sénégal",
    paymentHeading: "Choisissez votre règlement",
    paymentSubheading: "Deux modalités. La même pleine propriété.",
    upfrontLabel: "Le plus avantageux",
    upfrontTitle: "Paiement intégral",
    upfrontCopy: <>Réglez à la commande et bénéficiez immédiatement de <strong>5 % de réduction</strong>.</>,
    upfrontCta: "Choisir le paiement intégral",
    splitLabel: "Plus flexible",
    splitTitle: "Paiement échelonné",
    splitFirst: "60 % au démarrage",
    splitFinal: "40 % avant mise en ligne",
    splitCopy: "Commencez avec 60 %. Le solde est réglé après validation finale, juste avant la publication.",
    splitCta: "Choisir le paiement échelonné",
    noSubscription: "Zéro abonnement",
    noSubscriptionCopy: <>Après la livraison, vous ne payez que les renouvellements techniques auprès des fournisseurs concernés. Toute assistance STATURE reste facultative et fait l’objet d’une demande séparée.</>,
    experienceEyebrow: "Une expérience pensée pour vos clients",
    experienceTitle: <>Beau, oui.<br /><em>Mais surtout utile.</em></>,
    experienceCopy: "Un site STATURE guide naturellement le visiteur : il comprend votre valeur, trouve la bonne information et peut vous contacter immédiatement.",
    experienceItems: ["Jusqu’à 5 pages structurées autour de votre offre", "Mobile, WhatsApp, appels, Maps et formulaire", "SEO essentiel, statistiques, domaine et SSL"],
    experienceCta: "Voir notre méthode",
    processEyebrow: "La méthode STATURE",
    processTitle: <>Une démarche structurée.<br /><em>Un résultat qui vous ressemble.</em></>,
    process: [["01", "Comprendre", "Votre activité, vos clients et ce qui doit réellement changer."], ["02", "Structurer", "L’offre, les messages et le parcours qui rendent votre valeur évidente."], ["03", "Concevoir", "Une expérience rapide, distinctive et pensée pour la conversion."], ["04", "Livrer", "Mettre en ligne, transférer les accès et vous remettre un site qui vous appartient."]],
    originEyebrow: "Conçu à Dakar",
    originTitle: <>Une identité locale.<br /><em>Une exigence internationale.</em></>,
    originCopy: "STATURE comprend les réalités des entreprises sénégalaises et les transforme en une présence digitale claire, crédible et prête à soutenir leur croissance.",
    values: ["Proximité", "Clarté", "Crédibilité"],
    faqEyebrow: "Questions fréquentes",
    faqTitle: <>Tout comprendre<br /><em>avant de commencer.</em></>,
    faqIntro: "Une propriété complète, deux modalités de règlement et aucune obligation mensuelle dissimulée.",
    faqs: [
      ["Le site m’appartient-il vraiment ?", "Oui. Après règlement intégral, le site est installé dans des comptes à votre nom et vous recevez le code source, les fichiers ainsi que les accès nécessaires."],
      ["Quelle est la différence entre les deux paiements ?", "Le site livré est identique. Le paiement intégral accorde 5 % de réduction. Le paiement échelonné répartit le tarif normal en 60 % au démarrage et 40 % avant la mise en ligne."],
      ["Y a-t-il des frais mensuels obligatoires ?", "Non. Le domaine et l’hébergement doivent simplement être renouvelés auprès de leurs fournisseurs. Une assistance ponctuelle peut être demandée séparément."],
      ["Comment se déroule la remise du site ?", "STATURE installe le site, connecte le domaine, remet une archive complète du code et un guide de prise en main. Aucun mot de passe personnel n’est demandé."],
    ],
    contactEyebrow: "Votre aperçu personnalisé",
    contactTitle: <>Voyez votre futur site<br /><em>avant de décider.</em></>,
    contactCopy: "Présentez-nous votre activité au Sénégal. Nous préparons une première direction personnalisée sous 72 heures, sans engagement.",
    fields: { name: "Votre nom", company: "Organisation", phone: "Numéro de téléphone", market: "Votre marché", payment: "Modalité de paiement", message: "Parlez-nous du projet", placeholderName: "Aïssatou Ndiaye", placeholderCompany: "Nom de l’entreprise", placeholderPhone: "+221 77 000 00 00", placeholderMessage: "Votre activité, vos objectifs, votre délai...", submit: "Préparer ma demande", note: "Votre application e-mail va s’ouvrir avec la demande préremplie." },
    footerTagline: "Donnez à votre expertise la présence qu’elle mérite.",
    footerTop: "Haut de page",
    footerLocation: "Dakar, Sénégal",
  },
  FR: {
    lang: "fr",
    marketLabel: "France",
    marketEyebrow: "Pour les entreprises en France",
    pickerTitle: "Où se trouve votre entreprise ?",
    pickerCopy: "Choisissez votre marché pour afficher l’expérience, les tarifs et les modalités adaptés à votre pays.",
    pickerAction: "Voir la version France",
    nav: ["Le modèle", "Tarifs", "Méthode", "FAQ"],
    navCta: "Obtenir mon aperçu",
    heroEyebrow: "SOCLE — Site professionnel pour la France",
    heroTitle: <>Votre expertise mérite une présence à sa <em>hauteur.</em></>,
    heroLead: "Un site vitrine distinctif, rapide et entièrement à vous. Une collaboration francophone structurée, sans abonnement obligatoire.",
    heroPrimary: "Recevoir mon aperçu",
    heroSecondary: "Voir le tarif France",
    heroMeta: [["01 / Format", "Jusqu’à 5 pages"], ["02 / Aperçu", "Personnalisé sous 72 h"], ["03 / Livraison", "En 7 à 10 jours ouvrés"]],
    stripTitle: "Pensé pour les attentes du marché français",
    stripItems: ["Responsive", "Formulaire", "Google Maps", "SEO essentiel"],
    modelEyebrow: "Une alternative claire aux abonnements d’agence.",
    modelTitle: <>Une qualité professionnelle.<br /><em>Un prix maîtrisé, une liberté totale.</em></>,
    modelCopy: [
      "SOCLE donne aux indépendants, cabinets et PME une présence sobre et crédible : une offre facile à comprendre, un parcours fluide et des prises de contact sans friction.",
      "Vous achetez un actif, pas une location. Après le règlement, le site et ses accès vous sont transférés, sans engagement mensuel envers STATURE.",
    ],
    pricingEyebrow: "Tarif France",
    pricingTitle: <>Votre site en pleine propriété.<br />Deux façons de régler.</>,
    pricingIntro: "Un tarif fixe en euros, transparent dès le départ. Le paiement intégral est récompensé ; l’échelonnement préserve votre trésorerie.",
    offerBadge: "Pleine propriété",
    offerTitle: <>Votre site, vos accès.<br />Aucune dépendance.</>,
    offerCopy: "Conception, intégration, mise en ligne et transfert complet dans vos propres comptes.",
    features: ["Jusqu’à 5 pages personnalisées", "Design responsive et formulaire de contact", "Google Maps, SEO essentiel et statistiques", "Connexion du domaine et certificat SSL", "Code source et accès remis après règlement"],
    referencePrice: "Tarif de référence — France",
    paymentHeading: "Choisissez votre règlement",
    paymentSubheading: "Deux modalités. La même pleine propriété.",
    upfrontLabel: "Le plus avantageux",
    upfrontTitle: "Paiement intégral",
    upfrontCopy: <>Réglez à la commande et bénéficiez immédiatement de <strong>5 % de réduction</strong>.</>,
    upfrontCta: "Choisir le paiement intégral",
    splitLabel: "Plus flexible",
    splitTitle: "Paiement échelonné",
    splitFirst: "60 % au démarrage",
    splitFinal: "40 % avant mise en ligne",
    splitCopy: "Le projet démarre après le premier règlement. Le solde intervient après validation finale, avant la publication.",
    splitCta: "Choisir le paiement échelonné",
    noSubscription: "Sans abonnement",
    noSubscriptionCopy: <>Vous gardez la maîtrise de vos fournisseurs et de vos accès. Les renouvellements du domaine et de l’hébergement restent à votre nom ; l’assistance STATURE est facultative.</>,
    experienceEyebrow: "Une expérience qui inspire confiance",
    experienceTitle: <>Distinctif à l’écran.<br /><em>Efficace dans le parcours.</em></>,
    experienceCopy: "Chaque section aide le visiteur à comprendre votre valeur, vérifier votre crédibilité et passer naturellement à l’action.",
    experienceItems: ["Une structure claire autour de votre proposition de valeur", "Une expérience responsive sur mobile, tablette et ordinateur", "Des accès directs au formulaire, au téléphone et à votre adresse"],
    experienceCta: "Découvrir notre méthode",
    processEyebrow: "La méthode STATURE",
    processTitle: <>À distance, mais jamais distant.<br /><em>Un processus clair de bout en bout.</em></>,
    process: [["01", "Cadrer", "Nous clarifions votre activité, vos clients, vos objectifs et les contenus disponibles."], ["02", "Structurer", "Nous organisons l’offre et les messages pour rendre votre valeur immédiatement compréhensible."], ["03", "Concevoir", "Nous créons une expérience distinctive, responsive et orientée conversion."], ["04", "Transférer", "Nous publions le site dans vos comptes et vous remettons tous les accès nécessaires."]],
    originEyebrow: "Dakar × France",
    originTitle: <>Une production agile.<br /><em>Des standards internationaux.</em></>,
    originCopy: "Vous bénéficiez d’un interlocuteur francophone, d’horaires de collaboration compatibles et d’un processus documenté, de la première maquette jusqu’au transfert du site.",
    values: ["Francophone", "Structuré", "Transparent"],
    faqEyebrow: "Questions fréquentes",
    faqTitle: <>Une collaboration claire,<br /><em>même à distance.</em></>,
    faqIntro: "Le prix, les étapes, les droits et les livrables sont définis avant le démarrage du projet.",
    faqs: [
      ["Comment travailler avec une agence basée à Dakar ?", "Les échanges se font en français par visioconférence et e-mail, avec des validations écrites à chaque étape. Le décalage horaire reste faible et compatible avec les horaires de travail français."],
      ["Le site et le nom de domaine seront-ils à mon nom ?", "Oui. Le domaine et les comptes techniques sont créés à votre nom. Après paiement intégral, vous recevez également le code source et tous les accès."],
      ["Quelle est la différence entre les deux paiements ?", "Le paiement intégral accorde 5 % de réduction. Le paiement échelonné correspond à 60 % au démarrage et 40 % après validation finale, avant la mise en ligne."],
      ["Suis-je obligé de souscrire une maintenance ?", "Non. Aucune maintenance STATURE n’est obligatoire. Vous pouvez gérer le site vous-même ou demander une intervention ponctuelle lorsque nécessaire."],
    ],
    contactEyebrow: "Votre aperçu personnalisé",
    contactTitle: <>Projetez votre activité<br /><em>dans une présence plus forte.</em></>,
    contactCopy: "Présentez-nous votre entreprise en France. Nous préparons une première direction personnalisée sous 72 heures, sans engagement.",
    fields: { name: "Votre nom", company: "Entreprise", phone: "Numéro de téléphone", market: "Votre marché", payment: "Modalité de paiement", message: "Parlez-nous du projet", placeholderName: "Camille Martin", placeholderCompany: "Nom de l’entreprise", placeholderPhone: "+33 6 00 00 00 00", placeholderMessage: "Votre activité, vos objectifs, votre délai...", submit: "Préparer ma demande", note: "Votre application e-mail va s’ouvrir avec la demande préremplie." },
    footerTagline: "Donnez à votre expertise la présence qu’elle mérite.",
    footerTop: "Haut de page",
    footerLocation: "Dakar × France",
  },
  UK: {
    lang: "en",
    marketLabel: "United Kingdom",
    marketEyebrow: "For businesses in the United Kingdom",
    pickerTitle: "Where is your business based?",
    pickerCopy: "Choose your market to see the experience, pricing and payment terms tailored to your country.",
    pickerAction: "View the UK version",
    nav: ["The model", "Pricing", "Process", "FAQ"],
    navCta: "Get my preview",
    heroEyebrow: "SOCLE — Professional websites for the UK",
    heroTitle: <>A website that gives your expertise the <em>presence</em> it deserves.</>,
    heroLead: "A distinctive, fast and fully owned business website. Clear English-language collaboration with no compulsory subscription.",
    heroPrimary: "Get my tailored preview",
    heroSecondary: "View UK pricing",
    heroMeta: [["01 / Format", "Up to 5 pages"], ["02 / Preview", "Tailored within 72 hours"], ["03 / Delivery", "Within 7–10 working days"]],
    stripTitle: "Built around UK customer expectations",
    stripItems: ["Responsive", "Contact forms", "Google Maps", "Essential SEO"],
    modelEyebrow: "One investment. One digital asset you own.",
    modelTitle: <>Professional execution.<br /><em>Full ownership, complete freedom.</em></>,
    modelCopy: [
      "SOCLE gives consultants, practices and small businesses a polished online presence: a clear offer, a confident visual identity and a frictionless path to enquiry.",
      "You are purchasing an asset, not renting a website. Once the project is fully paid, the source code, files and technical access are transferred to you.",
    ],
    pricingEyebrow: "United Kingdom pricing",
    pricingTitle: <>Your website. Fully owned.<br />Two ways to pay.</>,
    pricingIntro: "A transparent fixed price in pounds sterling. Pay in full for the best value or split the investment across two project stages.",
    offerBadge: "Full ownership",
    offerTitle: <>Your website, your access.<br />No dependency.</>,
    offerCopy: "Design, development, launch and complete handover into accounts owned by your business.",
    features: ["Up to 5 tailored pages", "Responsive design and contact forms", "Google Maps, essential SEO and analytics", "Domain connection and SSL setup", "Source code and access transferred after payment"],
    referencePrice: "Reference price — United Kingdom",
    paymentHeading: "Choose how to pay",
    paymentSubheading: "Two options. The same full ownership.",
    upfrontLabel: "Best value",
    upfrontTitle: "Pay in full",
    upfrontCopy: <>Pay when the project starts and receive an immediate <strong>5% discount</strong>.</>,
    upfrontCta: "Choose full payment",
    splitLabel: "More flexible",
    splitTitle: "Split payment",
    splitFirst: "60% to begin",
    splitFinal: "40% before launch",
    splitCopy: "Work begins after the first payment. The balance is due after final approval and before the website goes live.",
    splitCta: "Choose split payment",
    noSubscription: "No subscription",
    noSubscriptionCopy: <>Your domain and hosting remain under your control. Ongoing STATURE support is optional and can be requested separately when needed.</>,
    experienceEyebrow: "An experience that builds confidence",
    experienceTitle: <>Distinctive by design.<br /><em>Useful at every step.</em></>,
    experienceCopy: "Every section helps visitors understand your value, verify your credibility and take the next step with confidence.",
    experienceItems: ["Up to 5 pages structured around your offer", "Responsive experience across mobile, tablet and desktop", "Direct access to forms, phone details and your location"],
    experienceCta: "See our process",
    processEyebrow: "The STATURE process",
    processTitle: <>Remote collaboration.<br /><em>Clear from start to handover.</em></>,
    process: [["01", "Discover", "We clarify your business, audience, objectives and available content."], ["02", "Structure", "We organise your offer and messaging so your value is immediately clear."], ["03", "Design", "We create a distinctive responsive experience built to generate enquiries."], ["04", "Hand over", "We launch the website in your accounts and transfer every required file and access."]],
    originEyebrow: "Dakar × United Kingdom",
    originTitle: <>Agile production.<br /><em>International standards.</em></>,
    originCopy: "You work with an English-speaking point of contact, a documented approval process and practical overlap with UK business hours—from the first concept to final handover.",
    values: ["English-speaking", "Structured", "Transparent"],
    faqEyebrow: "Frequently asked questions",
    faqTitle: <>Clear collaboration,<br /><em>wherever you are.</em></>,
    faqIntro: "Pricing, milestones, ownership and deliverables are agreed before work begins.",
    faqs: [
      ["How does working with a Dakar-based studio work?", "Communication is handled in English by video call and email, with written approval at each stage. Working hours provide practical overlap with the United Kingdom."],
      ["Will the website and domain be registered to my business?", "Yes. The domain and technical accounts are owned by you. Once payment is complete, you also receive the source code and all required access."],
      ["What is the difference between the two payment options?", "Full payment includes a 5% discount. Split payment is 60% when the project starts and 40% after final approval, before launch."],
      ["Do I have to purchase ongoing maintenance?", "No. There is no compulsory maintenance plan. You may manage the website independently or request one-off assistance when needed."],
    ],
    contactEyebrow: "Your tailored preview",
    contactTitle: <>See your future website<br /><em>before you decide.</em></>,
    contactCopy: "Tell us about your UK business. We will prepare an initial tailored direction within 72 hours, with no obligation.",
    fields: { name: "Your name", company: "Business", phone: "Phone number", market: "Your market", payment: "Payment option", message: "Tell us about the project", placeholderName: "Alex Morgan", placeholderCompany: "Business name", placeholderPhone: "+44 7700 900000", placeholderMessage: "Your business, objectives and preferred timeline...", submit: "Prepare my enquiry", note: "Your email app will open with a pre-filled enquiry." },
    footerTagline: "Give your expertise the presence it deserves.",
    footerTop: "Back to top",
    footerLocation: "Dakar × United Kingdom",
  },
} as const;
